spring:
  application:
    name: hana-dundun-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

# 외부 서비스 URL 설정
openbanking:
  base-url: https://open-banking-api.myhanati.site
  client-id: ${OPENBANKING_CLIENT_ID}
  client-secret: ${OPENBANKING_CLIENT_SECRET}

hanaBank:
  base-url: https://hana-bank-api.myhanati.site

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 86400000

# KOSIS API 설정
kosis:
  api:
    key: ${KOSIS_API_KEY}

# Gemini API 설정
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# 로깅 설정
logging:
  level:
    root: INFO
    com.hanadundun_backend: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/hana-dundun-backend.log
    max-size: 10MB
    max-history: 30

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: true
