-- 인덱스 삭제
DROP INDEX IDX_SHINHAN_USER_CI;
DROP INDEX IDX_SHINHAN_ACCOUNT_TYPE;

-- 트리거 삭제
DROP TRIGGER TRG_SHINHAN_BANK_TRANSACTION;
DROP TRIGGER TRG_SHINHAN_BANK_ACCOUNT;
DROP TRIGGER TRG_SHINHAN_BANK_USER;
DROP TRIGGER TRG_SHINHAN_IRP_ACCOUNT;
DROP TRIGGER TRG_SHINHAN_IRP_INVEST_PROD;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_SHINHAN_BANK_ACCOUNT_PRODUCT_ID;
DROP SEQUENCE SEQ_SHINHAN_BANK_TRANSACTION_ID;
DROP SEQUENCE SEQ_SHINHAN_BANK_ACCOUNT;
DROP SEQUENCE SEQ_SHINHAN_IRP_ACCOUNT_ID;
DROP SEQUENCE SEQ_SHINHAN_IRP_PROD_ID;

-- 테이블 삭제 (외래키 관계 순서 고려)
DROP TABLE SHINHAN_BANK_TRANSACTION;
DROP TABLE SHINHAN_BANK_ACCOUNT;
DROP TABLE SHINHAN_BANK_USER;
DROP TABLE SHINHAN_IRP_ACCOUNT;
DROP TABLE SHINHAN_IRP_INVESTMENT_PRODUCT;
