-- 신한은행 사용자 테이블
CREATE TABLE SHINHAN_BANK_USER (
    USER_ID      VARCHAR2(255 CHAR)   PRIMARY KEY,
    USER_CI      VARCHAR2(88 CHAR)    NOT NULL,
    USER_NUM     VARCHAR2(15 CHAR)    NOT NULL,
    USERNAME     VARCHAR2(100 CHAR)   NOT NULL,
    PHONE_NUMBER VARCHAR2(20 CHAR)    NOT NULL,
    EMAIL        VARCHAR2(100 CHAR)   NULL,
    CREATED_AT   TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
    UPDATED_AT   TIMESTAMP(6)         DEFAULT SYSTIMESTAMP
);

-- 신한은행 계좌 테이블
CREATE TABLE SHINHAN_BANK_ACCOUNT (
    ACCOUNT_ID              NUMBER               PRIMARY KEY,
    ACCOUNT_NUM             VARCHAR2(20 CHAR)    NOT NULL UNIQUE,
    USER_ID                 VARCHAR2(255 CHAR)   NOT NULL,
    BANK_CODE_STD           VARCHAR2(3 CHAR)     NOT NULL,
    ACTIVITY_TYPE           VARCHAR2(1 CHAR)     NOT NULL,
    ACCOUNT_TYPE            VARCHAR2(20 CHAR)    NOT NULL,
    ACCOUNT_NUM_MASKED      VARCHAR2(20 CHAR)    NOT NULL,
    ACCOUNT_SEQ             VARCHAR2(2 CHAR)     NOT NULL,
    ACCOUNT_LOCAL_CODE      VARCHAR2(7 CHAR)     NOT NULL,
    ACCOUNT_ISSUE_DATE      VARCHAR2(8 CHAR)     NOT NULL,
    MATURITY_DATE           VARCHAR2(8 CHAR)     NULL,
    LAST_TRAN_DATE          VARCHAR2(8 CHAR)     NOT NULL,
    PRODUCT_NAME            VARCHAR2(100 CHAR)   NOT NULL,
    PRODUCT_SUB_NAME        VARCHAR2(10 CHAR)    NULL,
    DORMANCY_YN             VARCHAR2(1 CHAR)     NOT NULL,
    BALANCE_AMT             NUMBER(15,2)         NOT NULL,
    DEPOSIT_AMT             NUMBER(15,2)         NULL,
    BALANCE_CALC_BASIS_1    VARCHAR2(1 CHAR)     NULL,
    BALANCE_CALC_BASIS_2    VARCHAR2(1 CHAR)     NULL,
    INVESTMENT_LINKED_YN    VARCHAR2(1 CHAR)     NULL,
    BANK_LINKED_YN          VARCHAR2(1 CHAR)     NULL,
    BALANCE_AFTER_CANCEL_YN VARCHAR2(1 CHAR)     NULL,
    SAVINGS_BANK_CODE       VARCHAR2(3 CHAR)     NULL,
    RETURN_RATE             DECIMAL(5,2)         NULL,
    RISK_LEVEL              NUMBER(1)            NULL,
    CREATED_AT              TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
    UPDATED_AT              TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES SHINHAN_BANK_USER(USER_ID),
    CONSTRAINT CHK_SHINHAN_RISK_LEVEL CHECK (risk_level IS NULL OR risk_level BETWEEN 1 AND 6),
    CONSTRAINT CHK_SHINHAN_RETURN_RATE CHECK (return_rate IS NULL OR return_rate >= 0),
    CONSTRAINT CHK_SHINHAN_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS', 'PENSION_FUND', 'PENSION_TRUST', 'PENSION_INSURANCE', 'IRP', 'STOCK')),
    CONSTRAINT CHK_SHINHAN_PENSION_INFO CHECK (
        (ACCOUNT_TYPE IN ('PENSION_FUND', 'PENSION_TRUST', 'PENSION_INSURANCE', 'IRP') AND return_rate IS NOT NULL AND risk_level IS NOT NULL)
        OR (ACCOUNT_TYPE NOT IN ('PENSION_FUND', 'PENSION_TRUST', 'PENSION_INSURANCE', 'IRP'))
    )
);

-- 신한은행 거래내역 테이블
CREATE TABLE SHINHAN_BANK_TRANSACTION (
    TRAN_ID            VARCHAR2(50 CHAR)    PRIMARY KEY,
    ACCOUNT_ID         NUMBER               NOT NULL,
    TRAN_DATE          DATE                 NOT NULL,
    TRAN_TIME          VARCHAR2(6 CHAR)     NOT NULL,
    INOUT_TYPE         VARCHAR2(8 CHAR)     NOT NULL,
    TRAN_TYPE          VARCHAR2(10 CHAR)    NULL,
    PRINT_CONTENT      VARCHAR2(20 CHAR)    NULL,
    TRAN_AMT           NUMBER(12,0)         NOT NULL,
    AFTER_BALANCE_AMT  NUMBER(13,0)         NULL,
    BRANCH_NAME        VARCHAR2(20 CHAR)    NULL,
    WD_BANK_CODE_STD   VARCHAR2(3 CHAR)     NOT NULL,
    WD_ACCOUNT_NUM     VARCHAR2(16 CHAR)    NOT NULL,
    REQ_CLIENT_NAME    VARCHAR2(20 CHAR)    NOT NULL,
    CREATED_AT         TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
    UPDATED_AT         TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES SHINHAN_BANK_ACCOUNT(ACCOUNT_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_SHINHAN_BANK_ACCOUNT
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE SEQ_SHINHAN_BANK_TRANSACTION_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE SEQ_SHINHAN_BANK_ACCOUNT_PRODUCT_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE SEQ_SHINHAN_IRP_ACCOUNT_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE SEQ_SHINHAN_IRP_PROD_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

-- 성능 최적화를 위한 인덱스 생성
CREATE INDEX IDX_SHINHAN_ACCOUNT_TYPE ON SHINHAN_BANK_ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX IDX_SHINHAN_USER_CI ON SHINHAN_BANK_ACCOUNT(USER_ID);

-- 컬럼 코멘트 추가
COMMENT ON COLUMN SHINHAN_BANK_ACCOUNT.RETURN_RATE IS '수익률 (연 % 단위) - 연금 상품 전용';
COMMENT ON COLUMN SHINHAN_BANK_ACCOUNT.RISK_LEVEL IS '위험도 (1=매우높음, 2=높음, 3=다소높음, 4=보통, 5=낮음, 6=매우낮음) - 연금 상품 전용';
COMMENT ON COLUMN SHINHAN_BANK_ACCOUNT.ACCOUNT_TYPE IS '계좌타입 (CHECKING=보통예금, SAVINGS=적금, PENSION_FUND=연금펀드, PENSION_TRUST=연금신탁, PENSION_INSURANCE=연금보험, STOCK=주식)';

-- 트리거 생성
CREATE OR REPLACE TRIGGER TRG_SHINHAN_BANK_USER
BEFORE INSERT OR UPDATE ON SHINHAN_BANK_USER
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SHINHAN_BANK_ACCOUNT
BEFORE INSERT OR UPDATE ON SHINHAN_BANK_ACCOUNT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ACCOUNT_ID IS NULL THEN
            :NEW.ACCOUNT_ID := SEQ_SHINHAN_BANK_ACCOUNT.NEXTVAL;
        END IF;
    END IF;
    
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SHINHAN_BANK_TRANSACTION
BEFORE INSERT OR UPDATE ON SHINHAN_BANK_TRANSACTION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.TRAN_ID IS NULL THEN
            :NEW.TRAN_ID := 'SH_TXN_' || TO_CHAR(SEQ_SHINHAN_BANK_TRANSACTION_ID.NEXTVAL, 'FM000000000');
        END IF;
    END IF;
    
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- 신한은행 IRP 계좌 테이블
CREATE TABLE SHINHAN_IRP_ACCOUNT (
    IRP_ID                  VARCHAR2(36 CHAR)    PRIMARY KEY,
    ACCOUNT_ID              VARCHAR2(255 CHAR)   NOT NULL,
    TOTAL_EVALUATION_AMOUNT NUMBER(15, 2)      NULL,
    YIELD_RATE              NUMBER(5, 2)       NULL,
    MATURITY_DATE           DATE                 NULL,
    WITHDRAWAL_LIMIT_YN     VARCHAR2(1 CHAR)     NULL,
    IRP_TYPE                VARCHAR2(20 CHAR)    NULL,
    IRP_STATUS              VARCHAR2(20 CHAR)    NULL,
    CREATED_AT              TIMESTAMP(6)         DEFAULT SYSTIMESTAMP,
    UPDATED_AT              TIMESTAMP(6)         DEFAULT SYSTIMESTAMP
);

-- 신한은행 IRP 투자 상품 테이블
CREATE TABLE SHINHAN_IRP_INVESTMENT_PRODUCT (
    PRODUCT_ID      VARCHAR2(36 CHAR)     PRIMARY KEY,
    IRP_ID          VARCHAR2(36 CHAR)     NOT NULL,
    PRODUCT_NAME    VARCHAR2(100 CHAR)    NOT NULL,
    BANK_CODE_STD   VARCHAR2(3 CHAR)      NOT NULL,
    INVEST_AMT      NUMBER(15, 2)       NULL,
    EXPECTED_YIELD  NUMBER(5, 2)        NULL,
    ACTUAL_YIELD    NUMBER(5, 2)        NULL,
    START_DATE      DATE                  NULL,
    MATURITY_DATE   DATE                  NULL,
    CREATED_AT      TIMESTAMP(6)          DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP(6)          DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (IRP_ID) REFERENCES SHINHAN_IRP_ACCOUNT(IRP_ID)
);

-- IRP 계좌 트리거
CREATE OR REPLACE TRIGGER TRG_SHINHAN_IRP_ACCOUNT
BEFORE INSERT OR UPDATE ON SHINHAN_IRP_ACCOUNT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.IRP_ID IS NULL THEN
            :NEW.IRP_ID := 'SH_IRP_' || TO_CHAR(SEQ_SHINHAN_IRP_ACCOUNT_ID.NEXTVAL, 'FM000000000');
        END IF;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- IRP 투자 상품 트리거
CREATE OR REPLACE TRIGGER TRG_SHINHAN_IRP_INVEST_PROD
BEFORE INSERT OR UPDATE ON SHINHAN_IRP_INVESTMENT_PRODUCT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.PRODUCT_ID IS NULL THEN
            :NEW.PRODUCT_ID := 'SH_IRP_PROD_' || TO_CHAR(SEQ_SHINHAN_IRP_PROD_ID.NEXTVAL, 'FM000000000');
        END IF;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/