-- 인덱스 삭제
DROP INDEX IDX_HANABANK_USER_CI;
DROP INDEX IDX_HANABANK_ACCOUNT_TYPE;

-- 트리거 삭제
DROP TRIGGER TRG_HANABANK_TRANSACTION;
DROP TRIGGER TRG_HANABANK_ACCOUNT;
DROP TRIGGER TRG_HANABANK_USER;
DROP TRIGGER TRG_HANABANK_IRP_ACCOUNT;
DROP TRIGGER TRG_HANABANK_IRP_INVEST_PROD;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_HANABANK_ACCOUNT_PRODUCT_ID;
DROP SEQUENCE SEQ_HANABANK_TRANSACTION_ID;
DROP SEQUENCE SEQ_HANABANK_ACCOUNT;
DROP SEQUENCE SEQ_HANABANK_IRP_ACCOUNT_ID;
DROP SEQUENCE SEQ_HANABANK_IRP_PROD_ID;

-- 테이블 삭제 (외래키 관계 순서 고려)
DROP TABLE HANABANK_TRANSACTION;
DROP TABLE HANABANK_ACCOUNT;
DROP TABLE HANABANK_USER;
DROP TABLE HANABANK_IRP_INVESTMENT_PRODUCT;
DROP TABLE HANABANK_IRP_INVESTMENT_PRODUCT;
