-- 인덱스 삭제
DROP INDEX IDX_OPENBANKING_TRANSACTION_LOG_TRAN_DATE;
DROP INDEX IDX_OPENBANKING_TRANSACTION_LOG_FINTECH;
DROP INDEX IDX_OPENBANKING_ACCOUNT_ACCOUNT_NUM;
DROP INDEX IDX_OPENBANKING_ACCOUNT_BANK_CODE;
DROP INDEX IDX_OPENBANKING_ACCOUNT_USER_SEQ_NO;
DROP INDEX IDX_OPENBANKING_USER_CI;

-- 트리거 삭제
DROP TRIGGER TRG_OPENBANKING_ACCOUNT;
DROP TRIGGER TRG_OPENBANKING_BANK_CODE;
DROP TRIGGER TRG_OPENBANKING_CLIENT;
DROP TRIGGER TRG_OPENBANKING_USER;

-- 시퀀스 삭제
DROP SEQUENCE TRANSACTION_SEQ;

-- 테이블 삭제 (외래키 관계 순서 고려)
DROP TABLE OPENBANKING_TRANSACTION_LOG;
DROP TABLE OPENBANKING_ACCOUNT;
DROP TABLE OPENBANKING_BANK_CODE;
DROP TABLE OPENBANKING_CLIENT;
DROP TABLE OPENBANKING_USER;