CREATE TABLE DB_LIFE_USER (
    USER_CI      VARCHAR2(88 CHAR)   PRIMARY KEY,
    USERNAME     VARCHAR2(100 CHAR)  NOT NULL,
    USER_INFO    VARCHAR2(8 CHAR)    NOT NULL,
    PHONE_NUMBER VARCHAR2(20 CHAR)   NOT NULL,
    EMAIL        VARCHAR2(100 CHAR)  NULL,
    CREATED_AT   TIMESTAMP(6)        NOT NULL,
    UPDATED_AT   TIMESTAMP(6)        NULL
);

-- CREATE TABLE DB_LIFE_INSURANCE_CODE (
--     INSU_TYPE CHAR(2 BYTE)         NOT NULL,
--     NAME      VARCHAR2(50 BYTE)    NOT NULL,
--     INSU_CODE VARCHAR2(10 BYTE)    NULL
-- );

CREATE TABLE DB_LIFE_CONTRACT (
    CONTRACT_ID          VARCHAR2(20 CHAR)    PRIMARY KEY,
    USER_CI              VARCHAR2(88 CHAR)    NOT NULL,
    INSU_STATUS          VARCHAR2(30 CHAR)    NOT NULL,
    INSU_TYPE            VARCHAR2(10 CHAR)    NOT NULL,
    PRODUCT_NAME         VARCHAR2(100 CHAR)   NOT NULL,
    CONTRACT_END_DATE    DATE,
    CONTRACT_START_DATE  DATE,
    MONTHLY_PREMIUM      NUMBER(10,0),
    IS_ACTIVE            VARCHAR2(1 CHAR),
    IS_TERMINATED        VARCHAR2(1 CHAR),
    CREATED_AT           TIMESTAMP(6)         NOT NULL,
    UPDATED_AT           TIMESTAMP(6),
    FOREIGN KEY (USER_CI) REFERENCES DB_LIFE_USER(USER_CI)
);

CREATE TABLE DB_LIFE_PRODUCT (
    INSU_TYPE VARCHAR2(2 CHAR)     PRIMARY KEY,
    NAME      VARCHAR2(50 CHAR)    NOT NULL,
    INSU_CODE VARCHAR2(10 CHAR)    NULL
);

CREATE TABLE DB_LIFE_INSURANCE_CODE_MAPPING (
    INSU_TYPE VARCHAR2(2 CHAR)     PRIMARY KEY,
    NAME      VARCHAR2(50 CHAR)    NOT NULL
);


CREATE SEQUENCE CONTRACT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER TRG_DB_LIFE_USER
BEFORE INSERT OR UPDATE ON DB_LIFE_USER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CREATED_AT IS NULL THEN
            :NEW.CREATED_AT := SYSTIMESTAMP;
        END IF;

        IF :NEW.UPDATED_AT IS NULL THEN
            :NEW.UPDATED_AT := SYSTIMESTAMP;
        END IF;
    END IF;

    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DB_LIFE_CONTRACT
BEFORE INSERT OR UPDATE ON DB_LIFE_CONTRACT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CONTRACT_ID IS NULL THEN
            :NEW.CONTRACT_ID := 'DB_LIFE_CONTRACT_' || TO_CHAR(CONTRACT_SEQ.NEXTVAL);
        END IF;
        
        IF :NEW.CREATED_AT IS NULL THEN
            :NEW.CREATED_AT := SYSTIMESTAMP;
        END IF;

        IF :NEW.UPDATED_AT IS NULL THEN
            :NEW.UPDATED_AT := SYSTIMESTAMP;
        END IF;
    END IF;

    IF UPDATING THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/