DROP TRIGGER TRG_DB_LIFE_CONTRACT;
DROP TRIGGER TRG_DB_LIFE_USER;

DROP SEQUENCE CONTRACT_SEQ;

DROP TABLE DB_LIFE_CONTRACT;
DROP TABLE DB_LIFE_PRODUCT;
DROP TABLE DB_LIFE_INSURANCE_CODE_MAPPING;
DROP TABLE DB_LIFE_USER;
